apiVersion: apps/v1
kind: Deployment
metadata:
  name: newworkflow
  labels:
    app: newworkflow
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1725521443929
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newworkflow
  template:
    metadata:
      labels:
        app: newworkflow
    spec:
      containers:
        - name: newworkflow
          image: acrworkflow1725521443929.azurecr.io/image-workflow-1725521443929:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
