apiVersion: apps/v1
kind: Deployment
metadata:
  name: different_repo
  labels:
    app: different_repo
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1725578335065
spec:
  replicas: 1
  selector:
    matchLabels:
      app: different_repo
  template:
    metadata:
      labels:
        app: different_repo
    spec:
      containers:
        - name: different_repo
          image: acrworkflow1725578335065.azurecr.io/image-workflow-1725578335065:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
