apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdf
  labels:
    app: sdf
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1727209553179
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdf
  template:
    metadata:
      labels:
        app: sdf
    spec:
      containers:
        - name: sdf
          image: acrworkflow1727209553179.azurecr.io/image-workflow-1727209553179:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
