apiVersion: apps/v1
kind: Deployment
metadata:
  name: differentrepo
  labels:
    app: differentrepo
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1725563810988
spec:
  replicas: 1
  selector:
    matchLabels:
      app: differentrepo
  template:
    metadata:
      labels:
        app: differentrepo
    spec:
      containers:
        - name: differentrepo
          image: acrworkflow1725563810988.azurecr.io/image-workflow-1725563810988:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
