apiVersion: apps/v1
kind: Deployment
metadata:
  name: wf1differentBranch
  labels:
    app: wf1differentBranch
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1725581919175
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wf1differentBranch
  template:
    metadata:
      labels:
        app: wf1differentBranch
    spec:
      containers:
        - name: wf1differentBranch
          image: acrworkflow1725581919175.azurecr.io/image-workflow-1725581919175:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
