apiVersion: apps/v1
kind: Deployment
metadata:
  name: diffRepo
  labels:
    app: diffRepo
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1727378042066
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diffRepo
  template:
    metadata:
      labels:
        app: diffRepo
    spec:
      containers:
        - name: diffRepo
          image: acrworkflow1727378042066.azurecr.io/image-workflow-1727378042066:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
