apiVersion: apps/v1
kind: Deployment
metadata:
  name: noserviceid
  labels:
    app: noserviceid
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1726785238197
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noserviceid
  template:
    metadata:
      labels:
        app: noserviceid
    spec:
      containers:
        - name: noserviceid
          image: acrworkflow1726785238197.azurecr.io/image-workflow-1726785238197:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
