apiVersion: v1
kind: Service
metadata:
  name: diffrepo
  namespace: namespace-workflow-1726175363172
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: diffrepo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000