apiVersion: v1
kind: Service
metadata:
  name: newworkflow
  namespace: namespace-workflow-1725521443929
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: newworkflow
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000