apiVersion: v1
kind: Service
metadata:
  name: sdf
  namespace: namespace-workflow-1727209553179
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: sdf
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000