apiVersion: v1
kind: Service
metadata:
  name: noserviceid
  namespace: namespace-workflow-1726785238197
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: noserviceid
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000