apiVersion: v1
kind: Service
metadata:
  name: differentrepo
  namespace: namespace-workflow-1725563810988
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: differentrepo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000