apiVersion: v1
kind: Service
metadata:
  name: different_repo
  namespace: namespace-workflow-1725578335065
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: different_repo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000