apiVersion: v1
kind: Service
metadata:
  name: wf1
  namespace: namespace-workflow-1725581155949
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: wf1
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000