apiVersion: v1
kind: Service
metadata:
  name: diffRepo
  namespace: namespace-workflow-1727378042066
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: diffRepo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000